name: Deploy
on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  deploymain:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 5
      - name: ftp-deploy-action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: o/p/apps/nankaidemo/
